name: Blue/Green Deployment
on:
  push:
    branches:
      - main
      - staging
env:
  APP_NAME: ${{ secrets.APP_NAME }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  BLUE_ENV: ${{ secrets.BLUE_ENV }}
  GREEN_ENV: ${{ secrets.GREEN_ENV }}
  PRODUCTION_CNAME: ${{ secrets.PRODUCTION_CNAME }}
  STAGING_CNAME: ${{ secrets.STAGING_CNAME }}

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get target EB environment name
        id: target-env
        run: node get-target-env.js
      - name: Generate staging deployment package
        run: echo "staging" > ENVIRONMENT && zip -r deploy.zip . -x '*.git*'
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.APP_NAME }}
          environment_name: ${{ steps.target-env.outputs.TARGET_ENV }}
          version_label: staging-${{ github.sha }}
          version_description: ${{ github.event.head_commit.message }}
          region: ${{ secrets.AWS_DEFAULT_REGION }}
          deployment_package: deploy.zip
          wait_for_environment_recovery: 60
          use_existing_version_if_available: true
      # here you can run e2e tests, etc., before deploying the production version

  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: ${{ github.ref_name == 'main' }}
    steps:
      - uses: actions/checkout@v3
      - name: Get target EB environment name
        id: target-env
        run: node get-target-env.js
      - name: Generate production deployment package
        run: echo "production" > ENVIRONMENT && zip -r deploy.zip . -x '*.git*'
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.APP_NAME }}
          environment_name: ${{ steps.target-env.outputs.TARGET_ENV }}
          version_label: staging-${{ github.sha }}
          version_description: ${{ github.event.head_commit.message }}
          region: ${{ secrets.AWS_DEFAULT_REGION }}
          deployment_package: deploy.zip
          wait_for_environment_recovery: 60
          use_existing_version_if_available: true
      - name: Swap CNAMEs
        run: node swap-cnames.js
