name: Blue/Green Deployment
on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get target EB environment name
        id: target-env
        run: |
          old_env=$(curl ${{ secrets.PROD_URL }}/api/server/info | jq '.EB_ENVIRONMENT' | sed 's/"//g')
          new_env=$([ $old_env == ${{ secrets.BLUE_ENV }} ] && echo ${{ secrets.GREEN_ENV }} || echo ${{ secrets.BLUE_ENV }})
          echo TARGET_ENV=$new_env >> $GITHUB_OUTPUT
      - name: Generate staging deployment package
        run: echo "staging" > ENVIRONMENT && zip -r deploy.zip . -x '*.git*'
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.APPLICATION_NAME }}
          environment_name: ${{ steps.target-env.outputs.TARGET_ENV }}
          version_label: staging-${{ github.sha }}
          version_description: ${{ github.event.head_commit.message }}
          region: ${{ secrets.AWS_DEFAULT_REGION }}
          deployment_package: deploy.zip
          wait_for_environment_recovery: 60
          use_existing_version_if_available: true
      - name: Wait for server
        run: |
          curl --retry 10 --retry-delay 10 --retry-connrefused ${{ secrets.STAGING_URL }}/api/server/info  || exit 1
    outputs:
      target: ${{ steps.target-env.outputs.TARGET_ENV }}
  promote:
    runs-on: ubuntu-latest
    needs: deploy
    # if: ${{ github.ref_name == 'main' }}
    steps:
      - uses: actions/checkout@v3
      - name: Generate production deployment package
        run: echo "production" > ENVIRONMENT && zip -r deploy.zip . -x '*.git*'
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.APPLICATION_NAME }}
          environment_name: ${{ needs.deploy.outputs.target }}
          version_label: production-${{ github.sha }}
          version_description: ${{ github.event.head_commit.message }}
          region: ${{ secrets.AWS_DEFAULT_REGION }}
          deployment_package: deploy.zip
          wait_for_environment_recovery: 60
          use_existing_version_if_available: true
      - name: Wait for server
        run: |
          curl --retry 10 --retry-delay 10 --retry-connrefused ${{ secrets.STAGING_URL }}/api/server/info  || exit 1
      - name: Swap CNAMEs
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          aws elasticbeanstalk swap-environment-cnames --source-environment-name ${{ secrets.BLUE_ENV }} --destination-environment-name ${{ secrets.GREEN_ENV }}
